### ISSUE TITLE
Doesn't build on Node 7.0.0

### ISSUE THREAD

**Issue by articice** [newghost/web-combiner#3]
Wouldn't build with newest NodeJS versions, probably with V8 API being changed.

```
../src/contextify.cc:150:16: error: 'class v8::ObjectTemplate' has no member named 'SetAccessCheckCallbacks'
         otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
```
plus emits a couple more deprecation warnings.

Node version is 7.0.0

Will test with 7.6.0
